[package]
name = "linkradar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
env_logger = "0.10.0"
fastping-rs = "0.2.3"
log = "0.4.17"
